// const mongoose = require('mongoose');
// const express = require('express');
// const router = express.Router();
// const Booking = require('../models/bookingModel');
// const Bus = require('../models/busModel');
// const Seat = require('../models/seat');
// const Route = require('../models/routesModel');
// const { verifyToken, isAdmin } = require('../middleware');

// // ============= CREATE BOOKING =============
// router.post('/', verifyToken, async (req, res) => {
//     const session = await mongoose.startSession();
//     session.startTransaction();
    
//     try {
//         const {
//             busId,
//             seats,
//             totalAmount,
//             taxAmount,
//             journeyDate,
//             paymentMethod,
//             paymentDetails,
//             boardingPoint
//         } = req.body;
        
//         // Validate required fields
//         if (!busId || !seats || !seats.length || !totalAmount || !paymentMethod || !journeyDate) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(400).json({
//                 success: false,
//                 message: 'Missing required fields'
//             });
//         }
        
//         // Get bus details
//         const bus = await Bus.findById(busId).session(session);
//         if (!bus) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(404).json({
//                 success: false,
//                 message: 'Bus not found'
//             });
//         }
        
//         // Get route details
//         const route = await Route.findById(bus.routeId).session(session);
//         if (!route) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(404).json({
//                 success: false,
//                 message: 'Route not found for this bus'
//             });
//         }
        
//         // Check if seats are still available
//         const bookedSeats = await Booking.find({
//             busId,
//             travelDate: new Date(journeyDate),
//             bookingStatus: 'confirmed',
//             paymentStatus: 'completed',
//             $or: [
//                 { 'selectedSeats.seatNumber': { $in: seats.map(s => s.seatNumber) } },
//                 { 'seats.seatNumber': { $in: seats.map(s => s.seatNumber) } }
//             ]
//         }).session(session);
        
//         if (bookedSeats.length > 0) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(400).json({
//                 success: false,
//                 message: 'Some seats are no longer available'
//             });
//         }
        
//         // Create booking (bookingId will be auto-generated by pre-save hook)
//         const booking = new Booking({
//             userId: req.user.userId,
//             busId: busId,
//             routeId: bus.routeId,
//             seats: seats.map(s => ({
//                 seatNumber: s.seatNumber,
//                 passengerName: s.passengerName,
//                 passengerAge: Number(s.passengerAge),
//                 passengerGender: s.passengerGender,
//                 passengerPhone: s.passengerPhone,
//                 passengerEmail: s.passengerEmail || ''
//             })),
//             selectedSeats: seats.map(s => ({
//                 seatNumber: s.seatNumber,
//                 seatType: 'passenger',
//                 price: totalAmount / seats.length
//             })),
//             passengerDetails: seats.map(s => ({
//                 name: s.passengerName,
//                 age: Number(s.passengerAge),
//                 gender: s.passengerGender,
//                 seatNumber: s.seatNumber,
//                 phone: s.passengerPhone,
//                 email: s.passengerEmail || ''
//             })),
//             totalAmount: Number(totalAmount),
//             taxAmount: Number(taxAmount) || 0,
//             paymentMethod: paymentMethod,
//             paymentStatus: paymentMethod === 'cash' ? 'pending' : 'completed',
//             paymentDetails: paymentDetails || {},
//             boardingPoint: boardingPoint || '',
//             bookingStatus: 'confirmed',
//             travelDate: new Date(journeyDate),
//             journeyDate: new Date(journeyDate),
//             contactNumber: seats[0]?.passengerPhone || '',
//             email: seats[0]?.passengerEmail || ''
//         });
        
//         await booking.save({ session });
        
//         // Update seat status if Seat model exists
//         if (Seat) {
//             await Seat.updateMany(
//                 {
//                     busId: busId,
//                     seatNumber: { $in: seats.map(s => s.seatNumber) }
//                 },
//                 { status: 'booked', bookedBy: req.user.userId, bookedAt: new Date() },
//                 { session }
//             );
//         }
        
//         await session.commitTransaction();
//         session.endSession();
        
//         // Populate and return the booking
//         const populatedBooking = await Booking.findById(booking._id)
//             .populate('busId', 'busName busNumber busType operator')
//             .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        
//         const responseData = {
//             _id: populatedBooking._id,
//             bookingId: populatedBooking.bookingId,
//             busDetails: {
//                 busName: populatedBooking.busId?.busName || 'N/A',
//                 busNumber: populatedBooking.busId?.busNumber || 'N/A',
//                 busType: populatedBooking.busId?.busType || 'N/A',
//                 operator: populatedBooking.busId?.operator || 'N/A'
//             },
//             routeDetails: {
//                 origin: populatedBooking.routeId?.origin || 'N/A',
//                 destination: populatedBooking.routeId?.destination || 'N/A',
//                 departureTime: populatedBooking.routeId?.departureTime || 'N/A',
//                 arrivalTime: populatedBooking.routeId?.arrivalTime || 'N/A',
//                 duration: populatedBooking.routeId?.duration || 'N/A',
//                 distance: populatedBooking.routeId?.distance || 0
//             },
//             seats: populatedBooking.seats,
//             passengers: populatedBooking.passengerDetails,
//             totalAmount: populatedBooking.totalAmount,
//             taxAmount: populatedBooking.taxAmount,
//             journeyDate: populatedBooking.journeyDate,
//             paymentMethod: populatedBooking.paymentMethod,
//             paymentStatus: populatedBooking.paymentStatus,
//             bookingStatus: populatedBooking.bookingStatus,
//             createdAt: populatedBooking.createdAt,
//             boardingPoint: populatedBooking.boardingPoint
//         };
        
//         res.status(201).json({
//             success: true,
//             message: 'Booking created successfully',
//             data: responseData
//         });
        
//     } catch (error) {
//         await session.abortTransaction();
//         session.endSession();
//         console.error('Error creating booking:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error creating booking',
//             error: error.message
//         });
//     }
// });

// // ============= GET AVAILABLE SEATS =============
// // router.get('/seats/available/:busId/:travelDate', verifyToken, async (req, res) => {
// //     try {
// //         const { busId, travelDate } = req.params;
        
// //         const allSeats = await Seat.find({ busId, isActive: true });
// //         const bookedSeats = await Booking.find({
// //             busId,
// //             travelDate: new Date(travelDate),
// //             bookingStatus: 'confirmed',
// //             paymentStatus: 'completed'
// //         }).select('selectedSeats seats');
        
// //         const bookedSeatNumbers = new Set();
// //         bookedSeats.forEach(booking => {
// //             if (booking.selectedSeats && booking.selectedSeats.length > 0) {
// //                 booking.selectedSeats.forEach(seat => bookedSeatNumbers.add(seat.seatNumber));
// //             }
// //             if (booking.seats && booking.seats.length > 0) {
// //                 booking.seats.forEach(seat => bookedSeatNumbers.add(seat.seatNumber));
// //             }
// //         });
        
// //         const seatsWithStatus = allSeats.map(seat => ({
// //             ...seat.toObject(),
// //             status: bookedSeatNumbers.has(seat.seatNumber) ? 'booked' : 'available'
// //         }));
        
// //         res.json({ success: true, data: seatsWithStatus });
// //     } catch (error) {
// //         console.error('Error fetching seats:', error);
// //         res.status(500).json({ success: false, message: 'Error fetching seats', error: error.message });
// //     }
// // });

// // ============= GET USER'S BOOKINGS =============
// router.get('/my-bookings', verifyToken, async (req, res) => {
//     try {
//         const bookings = await Booking.find({ userId: req.user.userId })
//             .populate('busId', 'busName busNumber busType operator')
//             .populate('routeId', 'origin destination departureTime arrivalTime duration')
//             .sort({ bookingDate: -1 });
        
//         const formattedBookings = bookings.map(booking => ({
//             _id: booking._id,
//             bookingId: booking.bookingId,
//             busDetails: {
//                 busName: booking.busId?.busName || 'N/A',
//                 busNumber: booking.busId?.busNumber || 'N/A',
//                 busType: booking.busId?.busType || 'N/A',
//                 operator: booking.busId?.operator || 'N/A'
//             },
//             routeDetails: {
//                 origin: booking.routeId?.origin || 'N/A',
//                 destination: booking.routeId?.destination || 'N/A',
//                 departureTime: booking.routeId?.departureTime || 'N/A',
//                 arrivalTime: booking.routeId?.arrivalTime || 'N/A',
//                 duration: booking.routeId?.duration || 'N/A'
//             },
//             seats: booking.seats,
//             totalAmount: booking.totalAmount,
//             taxAmount: booking.taxAmount,
//             journeyDate: booking.journeyDate,
//             paymentMethod: booking.paymentMethod,
//             paymentStatus: booking.paymentStatus,
//             bookingStatus: booking.bookingStatus,
//             createdAt: booking.createdAt,
//             boardingPoint: booking.boardingPoint
//         }));
        
//         res.json({ success: true, data: formattedBookings });
//     } catch (error) {
//         console.error('Error fetching bookings:', error);
//         res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
//     }
// });

// // ============= GET BOOKING BY ID =============
// router.get('/:bookingId', verifyToken, async (req, res) => {
//     try {
//         let booking;
        
//         if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
//             booking = await Booking.findById(req.params.bookingId)
//                 .populate('busId', 'busName busNumber busType operator')
//                 .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
//         }
        
//         if (!booking) {
//             booking = await Booking.findOne({ bookingId: req.params.bookingId })
//                 .populate('busId', 'busName busNumber busType operator')
//                 .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
//         }
        
//         if (!booking) {
//             return res.status(404).json({ success: false, message: 'Booking not found' });
//         }
        
//         if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
//             return res.status(403).json({ success: false, message: 'Access denied' });
//         }
        
//         res.json({
//             success: true,
//             data: {
//                 _id: booking._id,
//                 bookingId: booking.bookingId,
//                 busDetails: {
//                     busName: booking.busId?.busName || 'N/A',
//                     busNumber: booking.busId?.busNumber || 'N/A',
//                     busType: booking.busId?.busType || 'N/A',
//                     operator: booking.busId?.operator || 'N/A'
//                 },
//                 routeDetails: {
//                     origin: booking.routeId?.origin || 'N/A',
//                     destination: booking.routeId?.destination || 'N/A',
//                     departureTime: booking.routeId?.departureTime || 'N/A',
//                     arrivalTime: booking.routeId?.arrivalTime || 'N/A',
//                     duration: booking.routeId?.duration || 'N/A',
//                     distance: booking.routeId?.distance || 0
//                 },
//                 seats: booking.seats,
//                 passengers: booking.passengerDetails,
//                 totalAmount: booking.totalAmount,
//                 taxAmount: booking.taxAmount,
//                 journeyDate: booking.journeyDate,
//                 paymentMethod: booking.paymentMethod,
//                 paymentStatus: booking.paymentStatus,
//                 bookingStatus: booking.bookingStatus,
//                 createdAt: booking.createdAt,
//                 boardingPoint: booking.boardingPoint,
//                 contactNumber: booking.contactNumber,
//                 email: booking.email
//             }
//         });
//     } catch (error) {
//         console.error('Error fetching booking:', error);
//         res.status(500).json({ success: false, message: 'Error fetching booking', error: error.message });
//     }
// });

// // ============= CANCEL BOOKING =============
// router.put('/:bookingId/cancel', verifyToken, async (req, res) => {
//     const session = await mongoose.startSession();
//     session.startTransaction();
    
//     try {
//         const { cancellationReason } = req.body;
//         let booking;
        
//         if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
//             booking = await Booking.findById(req.params.bookingId).session(session);
//         }
        
//         if (!booking) {
//             booking = await Booking.findOne({ bookingId: req.params.bookingId }).session(session);
//         }
        
//         if (!booking) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(404).json({ success: false, message: 'Booking not found' });
//         }
        
//         if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(403).json({ success: false, message: 'Access denied' });
//         }
        
//         const travelDate = new Date(booking.travelDate);
//         const now = new Date();
//         const hoursDiff = (travelDate - now) / (1000 * 60 * 60);
        
//         if (hoursDiff < 2 && req.user.role !== 'admin') {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(400).json({ success: false, message: 'Cannot cancel booking within 2 hours of departure' });
//         }
        
//         let refundAmount = booking.totalAmount;
//         if (hoursDiff < 24 && hoursDiff >= 2) {
//             refundAmount = booking.totalAmount * 0.8;
//         } else if (hoursDiff < 2) {
//             refundAmount = 0;
//         }
        
//         booking.bookingStatus = 'cancelled';
//         booking.cancellationReason = cancellationReason;
//         booking.cancelledAt = new Date();
//         booking.refundAmount = refundAmount;
        
//         await booking.save({ session });
        
//         if (Seat) {
//             const seatNumbers = booking.seats.map(s => s.seatNumber);
//             await Seat.updateMany(
//                 { busId: booking.busId, seatNumber: { $in: seatNumbers } },
//                 { status: 'available', bookedBy: null, bookedAt: null },
//                 { session }
//             );
//         }
        
//         await session.commitTransaction();
//         session.endSession();
        
//         res.json({ success: true, message: 'Booking cancelled successfully', data: { bookingId: booking.bookingId, refundAmount } });
//     } catch (error) {
//         await session.abortTransaction();
//         session.endSession();
//         console.error('Error cancelling booking:', error);
//         res.status(500).json({ success: false, message: 'Error cancelling booking', error: error.message });
//     }
// });

// // ============= ADMIN: GET ALL BOOKINGS =============
// router.get('/admin/all', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const bookings = await Booking.find()
//             .populate('userId', 'firstName lastName email phone')
//             .populate('busId', 'busNumber busName busType operator')
//             .populate('routeId', 'origin destination')
//             .sort({ bookingDate: -1 });
        
//         res.json({ success: true, data: bookings });
//     } catch (error) {
//         console.error('Error fetching all bookings:', error);
//         res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
//     }
// });

// // ============= ADMIN: UPDATE BOOKING STATUS =============
// router.put('/admin/:bookingId/status', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const { status } = req.body;
//         let booking;
        
//         if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
//             booking = await Booking.findById(req.params.bookingId);
//         }
        
//         if (!booking) {
//             booking = await Booking.findOne({ bookingId: req.params.bookingId });
//         }
        
//         if (!booking) {
//             return res.status(404).json({ success: false, message: 'Booking not found' });
//         }
        
//         booking.bookingStatus = status;
//         await booking.save();
        
//         res.json({ success: true, message: 'Booking status updated successfully', data: booking });
//     } catch (error) {
//         console.error('Error updating booking status:', error);
//         res.status(500).json({ success: false, message: 'Error updating booking status', error: error.message });
//     }
// });
// // Add this endpoint to your booking routes file (after the existing routes)
// router.get('/admin/bus-seats/:busId/:journeyDate', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const { busId, journeyDate } = req.params;
        
//         // Get all seats for this bus
//         const allSeats = await Seat.find({ busId, isActive: true }).sort('seatNumber');
        
//         // Get all confirmed, paid bookings for this bus and date
//         const bookings = await Booking.find({
//             busId,
//             travelDate: new Date(journeyDate),
//             bookingStatus: { $in: ['confirmed', 'completed'] },
//             paymentStatus: 'completed'
//         }).populate('userId', 'firstName lastName phone');
        
//         // Collect all booked seats with passenger details
//         const bookedSeatsMap = new Map();
//         bookings.forEach(booking => {
//             booking.seats.forEach(seat => {
//                 bookedSeatsMap.set(seat.seatNumber, {
//                     seatNumber: seat.seatNumber,
//                     passengerName: seat.passengerName,
//                     passengerPhone: seat.passengerPhone,
//                     bookingId: booking.bookingId,
//                     userId: booking.userId,
//                     bookingStatus: booking.bookingStatus
//                 });
//             });
//         });
        
//         // Prepare seats with status and passenger info
//         const seatsWithStatus = allSeats.map(seat => {
//             const bookedInfo = bookedSeatsMap.get(seat.seatNumber);
//             return {
//                 ...seat.toObject(),
//                 status: bookedInfo ? 'booked' : 'available',
//                 passenger: bookedInfo || null
//             };
//         });
        
//         // Get bus details
//         const bus = await Bus.findById(busId).populate('routeId', 'origin destination departureTime arrivalTime');
        
//         res.json({
//             success: true,
//             data: {
//                 bus: bus,
//                 journeyDate: journeyDate,
//                 seats: seatsWithStatus,
//                 totalSeats: allSeats.length,
//                 bookedSeats: bookedSeatsMap.size,
//                 availableSeats: allSeats.length - bookedSeatsMap.size
//             }
//         });
//     } catch (error) {
//         console.error('Error fetching bus seats:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching bus seats',
//             error: error.message
//         });
//     }
// });




// // Add this after your existing routes in bookingRoute.js

// // ============= ADMIN: GET ALL BOOKINGS WITH FILTERS =============
// router.get('/admin/bookings', verifyToken, isAdmin, async (req, res) => {
//     try {
//         let query = {};
//         const { status, busId, paymentStatus, fromDate, toDate, search, page = 1, limit = 10 } = req.query;
        
//         // Apply filters
//         if (status && status !== 'all') {
//             query.bookingStatus = status;
//         }
        
//         if (busId && busId !== 'all') {
//             query.busId = busId;
//         }
        
//         if (paymentStatus && paymentStatus !== 'all') {
//             query.paymentStatus = paymentStatus;
//         }
        
//         // Date range filter
//         if (fromDate || toDate) {
//             query.travelDate = {};
//             if (fromDate) query.travelDate.$gte = new Date(fromDate);
//             if (toDate) query.travelDate.$lte = new Date(toDate);
//         }
        
//         // Search by booking ID, passenger name, or phone
//         if (search) {
//             query.$or = [
//                 { bookingId: { $regex: search, $options: 'i' } },
//                 { 'seats.passengerName': { $regex: search, $options: 'i' } },
//                 { 'seats.passengerPhone': { $regex: search, $options: 'i' } },
//                 { contactNumber: { $regex: search, $options: 'i' } }
//             ];
//         }
        
//         const skip = (parseInt(page) - 1) * parseInt(limit);
        
//         const bookings = await Booking.find(query)
//             .populate('busId', 'busName busNumber busType operator')
//             .populate('routeId', 'origin destination departureTime arrivalTime duration distance')
//             .populate('userId', 'firstName lastName email phone')
//             .sort({ bookingDate: -1 })
//             .skip(skip)
//             .limit(parseInt(limit));
        
//         const total = await Booking.countDocuments(query);
        
//         // Format bookings for frontend
//         const formattedBookings = bookings.map(booking => ({
//             _id: booking._id,
//             bookingId: booking.bookingId,
//             userId: booking.userId,
//             busId: booking.busId,
//             busDetails: {
//                 _id: booking.busId?._id,
//                 busName: booking.busId?.busName || 'N/A',
//                 busNumber: booking.busId?.busNumber || 'N/A',
//                 busType: booking.busId?.busType || 'N/A',
//                 operator: booking.busId?.operator || 'N/A'
//             },
//             routeDetails: {
//                 origin: booking.routeId?.origin || 'N/A',
//                 destination: booking.routeId?.destination || 'N/A',
//                 departureTime: booking.routeId?.departureTime || 'N/A',
//                 arrivalTime: booking.routeId?.arrivalTime || 'N/A',
//                 duration: booking.routeId?.duration || 'N/A',
//                 distance: booking.routeId?.distance || 0
//             },
//             seats: booking.seats,
//             passengerDetails: booking.passengerDetails,
//             totalAmount: booking.totalAmount,
//             taxAmount: booking.taxAmount,
//             bookingDate: booking.bookingDate,
//             journeyDate: booking.journeyDate,
//             travelDate: booking.travelDate,
//             status: booking.bookingStatus,
//             bookingStatus: booking.bookingStatus,
//             paymentStatus: booking.paymentStatus,
//             paymentMethod: booking.paymentMethod,
//             cancellationDetails: booking.cancelledAt ? {
//                 cancelledAt: booking.cancelledAt,
//                 refundAmount: booking.refundAmount,
//                 reason: booking.cancellationReason
//             } : undefined,
//             userDetails: booking.userId ? {
//                 firstName: booking.userId.firstName,
//                 lastName: booking.userId.lastName,
//                 email: booking.userId.email,
//                 phone: booking.userId.phone
//             } : undefined,
//             createdAt: booking.createdAt,
//             updatedAt: booking.updatedAt
//         }));
        
//         res.json({
//             success: true,
//             data: formattedBookings,
//             count: total,
//             page: parseInt(page),
//             totalPages: Math.ceil(total / parseInt(limit))
//         });
        
//     } catch (error) {
//         console.error('Error fetching bookings:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching bookings',
//             error: error.message
//         });
//     }
// });

// // ============= ADMIN: GET BOOKING STATISTICS =============
// router.get('/admin/statistics', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const { period = 'thisMonth' } = req.query;
        
//         let startDate, endDate = new Date();
        
//         // Calculate date range based on period
//         switch(period) {
//             case 'today':
//                 startDate = new Date();
//                 startDate.setHours(0, 0, 0, 0);
//                 break;
//             case 'yesterday':
//                 startDate = new Date();
//                 startDate.setDate(startDate.getDate() - 1);
//                 startDate.setHours(0, 0, 0, 0);
//                 endDate = new Date(startDate);
//                 endDate.setHours(23, 59, 59, 999);
//                 break;
//             case 'thisWeek':
//                 startDate = new Date();
//                 startDate.setDate(startDate.getDate() - startDate.getDay());
//                 startDate.setHours(0, 0, 0, 0);
//                 break;
//             case 'thisMonth':
//                 startDate = new Date();
//                 startDate.setDate(1);
//                 startDate.setHours(0, 0, 0, 0);
//                 break;
//             case 'lastMonth':
//                 startDate = new Date();
//                 startDate.setMonth(startDate.getMonth() - 1);
//                 startDate.setDate(1);
//                 startDate.setHours(0, 0, 0, 0);
//                 endDate = new Date(startDate);
//                 endDate.setMonth(endDate.getMonth() + 1);
//                 endDate.setDate(0);
//                 endDate.setHours(23, 59, 59, 999);
//                 break;
//             case 'last3Months':
//                 startDate = new Date();
//                 startDate.setMonth(startDate.getMonth() - 3);
//                 startDate.setDate(1);
//                 startDate.setHours(0, 0, 0, 0);
//                 break;
//             default:
//                 startDate = new Date();
//                 startDate.setDate(1);
//                 startDate.setHours(0, 0, 0, 0);
//         }
        
//         // Build query for date range
//         let dateQuery = {};
//         if (startDate) dateQuery.$gte = startDate;
//         if (endDate) dateQuery.$lte = endDate;
        
//         const dateFilter = Object.keys(dateQuery).length > 0 ? { bookingDate: dateQuery } : {};
        
//         // Get statistics
//         const totalBookings = await Booking.countDocuments(dateFilter);
//         const totalRevenue = await Booking.aggregate([
//             { $match: { ...dateFilter, paymentStatus: 'completed', bookingStatus: { $ne: 'cancelled' } } },
//             { $group: { _id: null, total: { $sum: { $add: ['$totalAmount', '$taxAmount'] } } } }
//         ]);
        
//         const confirmedBookings = await Booking.countDocuments({ ...dateFilter, bookingStatus: 'confirmed' });
//         const cancelledBookings = await Booking.countDocuments({ ...dateFilter, bookingStatus: 'cancelled' });
//         const pendingBookings = await Booking.countDocuments({ ...dateFilter, bookingStatus: 'pending' });
//         const completedBookings = await Booking.countDocuments({ ...dateFilter, bookingStatus: 'completed' });
        
//         // Today's bookings
//         const today = new Date();
//         today.setHours(0, 0, 0, 0);
//         const tomorrow = new Date(today);
//         tomorrow.setDate(tomorrow.getDate() + 1);
        
//         const todayBookings = await Booking.countDocuments({
//             bookingDate: { $gte: today, $lt: tomorrow }
//         });
        
//         // Weekly bookings (last 7 days)
//         const weekAgo = new Date();
//         weekAgo.setDate(weekAgo.getDate() - 7);
//         const weeklyBookings = await Booking.countDocuments({
//             bookingDate: { $gte: weekAgo }
//         });
        
//         // Monthly bookings (last 30 days)
//         const monthAgo = new Date();
//         monthAgo.setDate(monthAgo.getDate() - 30);
//         const monthlyBookings = await Booking.countDocuments({
//             bookingDate: { $gte: monthAgo }
//         });
        
//         const stats = {
//             totalBookings,
//             totalRevenue: totalRevenue[0]?.total || 0,
//             confirmedBookings,
//             cancelledBookings,
//             pendingBookings,
//             completedBookings,
//             averageBookingValue: totalBookings > 0 ? (totalRevenue[0]?.total || 0) / totalBookings : 0,
//             todayBookings,
//             weeklyBookings,
//             monthlyBookings
//         };
        
//         res.json({
//             success: true,
//             data: stats
//         });
        
//     } catch (error) {
//         console.error('Error fetching statistics:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching statistics',
//             error: error.message
//         });
//     }
// });

// // ============= ADMIN: UPDATE BOOKING STATUS (already exists, but ensure path matches) =============
// // This route already exists in your code: router.put('/admin/:bookingId/status', ...)
// // Make sure it's not commented out

// // ============= ADMIN: EXPORT BOOKINGS =============
// router.get('/admin/bookings/export', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const { status, busId, paymentStatus, fromDate, toDate, search } = req.query;
        
//         let query = {};
        
//         // Apply same filters as above
//         if (status && status !== 'all') query.bookingStatus = status;
//         if (busId && busId !== 'all') query.busId = busId;
//         if (paymentStatus && paymentStatus !== 'all') query.paymentStatus = paymentStatus;
//         if (fromDate || toDate) {
//             query.travelDate = {};
//             if (fromDate) query.travelDate.$gte = new Date(fromDate);
//             if (toDate) query.travelDate.$lte = new Date(toDate);
//         }
//         if (search) {
//             query.$or = [
//                 { bookingId: { $regex: search, $options: 'i' } },
//                 { 'seats.passengerName': { $regex: search, $options: 'i' } }
//             ];
//         }
        
//         const bookings = await Booking.find(query)
//             .populate('busId', 'busName busNumber')
//             .populate('routeId', 'origin destination')
//             .sort({ bookingDate: -1 });
        
//         // Format for CSV/Excel
//         const exportData = bookings.map(booking => ({
//             'Booking ID': booking.bookingId,
//             'Passenger Name': booking.seats[0]?.passengerName || 'N/A',
//             'Phone': booking.seats[0]?.passengerPhone || 'N/A',
//             'Bus': `${booking.busId?.busName} (${booking.busId?.busNumber})`,
//             'Route': `${booking.routeId?.origin} → ${booking.routeId?.destination}`,
//             'Journey Date': booking.journeyDate.toISOString().split('T')[0],
//             'Seats': booking.seats.map(s => s.seatNumber).join(', '),
//             'Total Amount': booking.totalAmount + booking.taxAmount,
//             'Status': booking.bookingStatus,
//             'Payment Status': booking.paymentStatus,
//             'Booking Date': booking.bookingDate.toISOString().split('T')[0]
//         }));
        
//         // Send as JSON for now (you can implement CSV conversion later)
//         res.json({
//             success: true,
//             data: exportData
//         });
        
//     } catch (error) {
//         console.error('Error exporting bookings:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error exporting bookings',
//             error: error.message
//         });
//     }
// });

// // Add this at the end of your bookingRoute.js file, before module.exports
// // ============= PUBLIC: GET AVAILABLE SEATS (No authentication) =============
// // router.get('/public/seats/available/:busId/:travelDate', async (req, res) => {
// //     try {
// //         const { busId, travelDate } = req.params;
        
// //         console.log(`🔍 [PUBLIC] Checking available seats for bus ${busId} on date ${travelDate}`);
        
// //         // Parse the date correctly
// //         const startDate = new Date(travelDate);
// //         startDate.setHours(0, 0, 0, 0);
// //         const endDate = new Date(travelDate);
// //         endDate.setHours(23, 59, 59, 999);
        
// //         // Find all confirmed/completed bookings for this bus on this date
// //         const bookings = await Booking.find({
// //             busId: busId,
// //             travelDate: { $gte: startDate, $lte: endDate },
// //             bookingStatus: { $in: ['confirmed', 'completed'] },
// //             paymentStatus: { $in: ['paid', 'completed'] }
// //         });
        
// //         console.log(`Found ${bookings.length} bookings for bus ${busId} on ${travelDate}`);
        
// //         // Collect all booked seats with details
// //         const bookedSeats = [];
// //         bookings.forEach(booking => {
// //             if (booking.seats && booking.seats.length > 0) {
// //                 booking.seats.forEach(seat => {
// //                     bookedSeats.push({
// //                         seatNumber: seat.seatNumber,
// //                         passengerName: seat.passengerName,
// //                         passengerPhone: seat.passengerPhone,
// //                         bookingId: booking.bookingId
// //                     });
// //                     console.log(`Booked seat: ${seat.seatNumber}`);
// //                 });
// //             }
// //         });
        
// //         console.log(`Total booked seats: ${bookedSeats.length}`);
        
// //         res.json({
// //             success: true,
// //             data: bookedSeats,
// //             count: bookedSeats.length,
// //             busId: busId,
// //             travelDate: travelDate
// //         });
        
// //     } catch (error) {
// //         console.error('Error fetching available seats:', error);
// //         res.status(500).json({
// //             success: false,
// //             message: 'Error fetching seats',
// //             error: error.message
// //         });
// //     }
// // });
// // ============= GET AVAILABLE SEATS =============
// // UNCOMMENT THIS ENDPOINT - IT'S THE ONE YOUR FRONTEND IS CALLING
// router.get('/seats/available/:busId/:travelDate', verifyToken, async (req, res) => {
//     try {
//         const { busId, travelDate } = req.params;
        
//         console.log(`🔍 Checking available seats for bus ${busId} on date ${travelDate}`);
        
//         // Parse the date correctly
//         const startDate = new Date(travelDate);
//         startDate.setHours(0, 0, 0, 0);
//         const endDate = new Date(travelDate);
//         endDate.setHours(23, 59, 59, 999);
        
//         // Find all confirmed/completed bookings for this bus on this date
//         const bookings = await Booking.find({
//             busId: busId,
//             travelDate: { $gte: startDate, $lte: endDate },
//             bookingStatus: { $in: ['confirmed', 'completed'] },
//             paymentStatus: 'completed'
//         });
        
//         console.log(`Found ${bookings.length} bookings for bus ${busId} on ${travelDate}`);
        
//         // Collect all booked seats with details
//         const bookedSeats = [];
//         bookings.forEach(booking => {
//             if (booking.seats && booking.seats.length > 0) {
//                 booking.seats.forEach(seat => {
//                     bookedSeats.push({
//                         seatNumber: seat.seatNumber,
//                         passengerName: seat.passengerName,
//                         passengerPhone: seat.passengerPhone,
//                         bookingId: booking.bookingId
//                     });
//                     console.log(`Booked seat: ${seat.seatNumber}`);
//                 });
//             }
//         });
        
//         console.log(`Total booked seats: ${bookedSeats.length}`);
        
//         res.json({
//             success: true,
//             data: bookedSeats,
//             count: bookedSeats.length
//         });
        
//     } catch (error) {
//         console.error('Error fetching available seats:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching seats',
//             error: error.message
//         });
//     }
// });
// module.exports = router;


const mongoose = require('mongoose');
const express = require('express');
const router = express.Router();
const Booking = require('../models/bookingModel');
const Bus = require('../models/busModel');
const Seat = require('../models/seat');
const Route = require('../models/routesModel');
const { verifyToken, isAdmin } = require('../middleware');

// ============= CREATE BOOKING =============
router.post('/', verifyToken, async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const {
            busId,
            seats,
            totalAmount,
            taxAmount,
            journeyDate,
            paymentMethod,
            paymentDetails,
            boardingPoint
        } = req.body;
        
        // Validate required fields
        if (!busId || !seats || !seats.length || !totalAmount || !paymentMethod || !journeyDate) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Missing required fields'
            });
        }
        
        // Get bus details
        const bus = await Bus.findById(busId).session(session);
        if (!bus) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Bus not found'
            });
        }
        
        // Get route details
        const route = await Route.findById(bus.routeId).session(session);
        if (!route) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Route not found for this bus'
            });
        }
        
        // Check if seats are still available
        const bookedSeats = await Booking.find({
            busId,
            travelDate: new Date(journeyDate),
            bookingStatus: 'confirmed',
            paymentStatus: 'completed',
            $or: [
                { 'selectedSeats.seatNumber': { $in: seats.map(s => s.seatNumber) } },
                { 'seats.seatNumber': { $in: seats.map(s => s.seatNumber) } }
            ]
        }).session(session);
        
        if (bookedSeats.length > 0) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Some seats are no longer available'
            });
        }
        
        // Create booking (bookingId will be auto-generated by pre-save hook)
        const booking = new Booking({
            userId: req.user.userId,
            busId: busId,
            routeId: bus.routeId,
            seats: seats.map(s => ({
                seatNumber: s.seatNumber,
                passengerName: s.passengerName,
                passengerAge: Number(s.passengerAge),
                passengerGender: s.passengerGender,
                passengerPhone: s.passengerPhone,
                passengerEmail: s.passengerEmail || ''
            })),
            selectedSeats: seats.map(s => ({
                seatNumber: s.seatNumber,
                seatType: 'passenger',
                price: totalAmount / seats.length
            })),
            passengerDetails: seats.map(s => ({
                name: s.passengerName,
                age: Number(s.passengerAge),
                gender: s.passengerGender,
                seatNumber: s.seatNumber,
                phone: s.passengerPhone,
                email: s.passengerEmail || ''
            })),
            totalAmount: Number(totalAmount),
            taxAmount: Number(taxAmount) || 0,
            paymentMethod: paymentMethod,
            paymentStatus: paymentMethod === 'cash' ? 'pending' : 'completed',
            paymentDetails: paymentDetails || {},
            boardingPoint: boardingPoint || '',
            bookingStatus: 'confirmed',
            travelDate: new Date(journeyDate),
            journeyDate: new Date(journeyDate),
            contactNumber: seats[0]?.passengerPhone || '',
            email: seats[0]?.passengerEmail || ''
        });
        
        await booking.save({ session });
        
        // Update seat status if Seat model exists
        if (Seat) {
            await Seat.updateMany(
                {
                    busId: busId,
                    seatNumber: { $in: seats.map(s => s.seatNumber) }
                },
                { status: 'booked', bookedBy: req.user.userId, bookedAt: new Date() },
                { session }
            );
        }
        
        await session.commitTransaction();
        session.endSession();
        
        // Populate and return the booking
        const populatedBooking = await Booking.findById(booking._id)
            .populate('busId', 'busName busNumber busType operator')
            .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        
        const responseData = {
            _id: populatedBooking._id,
            bookingId: populatedBooking.bookingId,
            busDetails: {
                busName: populatedBooking.busId?.busName || 'N/A',
                busNumber: populatedBooking.busId?.busNumber || 'N/A',
                busType: populatedBooking.busId?.busType || 'N/A',
                operator: populatedBooking.busId?.operator || 'N/A'
            },
            routeDetails: {
                origin: populatedBooking.routeId?.origin || 'N/A',
                destination: populatedBooking.routeId?.destination || 'N/A',
                departureTime: populatedBooking.routeId?.departureTime || 'N/A',
                arrivalTime: populatedBooking.routeId?.arrivalTime || 'N/A',
                duration: populatedBooking.routeId?.duration || 'N/A',
                distance: populatedBooking.routeId?.distance || 0
            },
            seats: populatedBooking.seats,
            passengers: populatedBooking.passengerDetails,
            totalAmount: populatedBooking.totalAmount,
            taxAmount: populatedBooking.taxAmount,
            journeyDate: populatedBooking.journeyDate,
            paymentMethod: populatedBooking.paymentMethod,
            paymentStatus: populatedBooking.paymentStatus,
            bookingStatus: populatedBooking.bookingStatus,
            createdAt: populatedBooking.createdAt,
            boardingPoint: populatedBooking.boardingPoint
        };
        
        res.status(201).json({
            success: true,
            message: 'Booking created successfully',
            data: responseData
        });
        
    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        console.error('Error creating booking:', error);
        res.status(500).json({
            success: false,
            message: 'Error creating booking',
            error: error.message
        });
    }
});

// ============= GET AVAILABLE SEATS (WORKING ENDPOINT) =============
// router.get('/seats/available/:busId/:travelDate', verifyToken, async (req, res) => {
//     try {
//         const { busId, travelDate } = req.params;
        
//         console.log(`🔍 Checking available seats for bus ${busId} on date ${travelDate}`);
        
//         // Parse the date correctly for full day
//         const startDate = new Date(travelDate);
//         startDate.setHours(0, 0, 0, 0);
//         const endDate = new Date(travelDate);
//         endDate.setHours(23, 59, 59, 999);
        
//         // Find all confirmed/completed bookings for this bus on this date
//         const bookings = await Booking.find({
//             busId: busId,
//             travelDate: { $gte: startDate, $lte: endDate },
//             bookingStatus: { $in: ['confirmed', 'completed'] },
//             paymentStatus: 'completed'
//         }).select('seats selectedSeats bookingId');
        
//         console.log(`Found ${bookings.length} bookings for bus ${busId} on ${travelDate}`);
        
//         // Collect all booked seats with details
//         const bookedSeats = [];
//         bookings.forEach(booking => {
//             // Check seats array
//             if (booking.seats && booking.seats.length > 0) {
//                 booking.seats.forEach(seat => {
//                     if (seat && seat.seatNumber) {
//                         bookedSeats.push({
//                             seatNumber: seat.seatNumber,
//                             passengerName: seat.passengerName || 'Unknown',
//                             passengerPhone: seat.passengerPhone || 'N/A',
//                             bookingId: booking.bookingId,
//                             status: 'booked'
//                         });
//                         console.log(`📌 Booked seat: ${seat.seatNumber}`);
//                     }
//                 });
//             }
            
//             // Check selectedSeats array (backward compatibility)
//             if (booking.selectedSeats && booking.selectedSeats.length > 0) {
//                 booking.selectedSeats.forEach(seat => {
//                     if (seat && seat.seatNumber) {
//                         bookedSeats.push({
//                             seatNumber: seat.seatNumber,
//                             passengerName: 'Booked',
//                             passengerPhone: 'N/A',
//                             bookingId: booking.bookingId,
//                             status: 'booked'
//                         });
//                         console.log(`📌 Booked seat (selected): ${seat.seatNumber}`);
//                     }
//                 });
//             }
//         });
        
//         // Remove duplicates (in case a seat appears in both arrays)
//         const uniqueBookedSeats = [];
//         const seenSeats = new Set();
//         for (const seat of bookedSeats) {
//             if (!seenSeats.has(seat.seatNumber)) {
//                 seenSeats.add(seat.seatNumber);
//                 uniqueBookedSeats.push(seat);
//             }
//         }
        
//         console.log(`✅ Total unique booked seats: ${uniqueBookedSeats.length}`);
//         console.log(`📋 Booked seat numbers:`, uniqueBookedSeats.map(s => s.seatNumber));
        
//         res.json({
//             success: true,
//             data: uniqueBookedSeats,
//             count: uniqueBookedSeats.length
//         });
        
//     } catch (error) {
//         console.error('❌ Error fetching available seats:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching seats',
//             error: error.message
//         });
//     }
// });

// ============= GET USER'S BOOKINGS =============
router.get('/my-bookings', verifyToken, async (req, res) => {
    try {
        const bookings = await Booking.find({ userId: req.user.userId })
            .populate('busId', 'busName busNumber busType operator')
            .populate('routeId', 'origin destination departureTime arrivalTime duration')
            .sort({ bookingDate: -1 });
        
        const formattedBookings = bookings.map(booking => ({
            _id: booking._id,
            bookingId: booking.bookingId,
            busDetails: {
                busName: booking.busId?.busName || 'N/A',
                busNumber: booking.busId?.busNumber || 'N/A',
                busType: booking.busId?.busType || 'N/A',
                operator: booking.busId?.operator || 'N/A'
            },
            routeDetails: {
                origin: booking.routeId?.origin || 'N/A',
                destination: booking.routeId?.destination || 'N/A',
                departureTime: booking.routeId?.departureTime || 'N/A',
                arrivalTime: booking.routeId?.arrivalTime || 'N/A',
                duration: booking.routeId?.duration || 'N/A'
            },
            seats: booking.seats,
            totalAmount: booking.totalAmount,
            taxAmount: booking.taxAmount,
            journeyDate: booking.journeyDate,
            paymentMethod: booking.paymentMethod,
            paymentStatus: booking.paymentStatus,
            bookingStatus: booking.bookingStatus,
            createdAt: booking.createdAt,
            boardingPoint: booking.boardingPoint
        }));
        
        res.json({ success: true, data: formattedBookings });
    } catch (error) {
        console.error('Error fetching bookings:', error);
        res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
    }
});

// ============= GET BOOKING BY ID =============
router.get('/:bookingId', verifyToken, async (req, res) => {
    try {
        let booking;
        
        if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
            booking = await Booking.findById(req.params.bookingId)
                .populate('busId', 'busName busNumber busType operator')
                .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        }
        
        if (!booking) {
            booking = await Booking.findOne({ bookingId: req.params.bookingId })
                .populate('busId', 'busName busNumber busType operator')
                .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        }
        
        if (!booking) {
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        
        if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        
        res.json({
            success: true,
            data: {
                _id: booking._id,
                bookingId: booking.bookingId,
                busDetails: {
                    busName: booking.busId?.busName || 'N/A',
                    busNumber: booking.busId?.busNumber || 'N/A',
                    busType: booking.busId?.busType || 'N/A',
                    operator: booking.busId?.operator || 'N/A'
                },
                routeDetails: {
                    origin: booking.routeId?.origin || 'N/A',
                    destination: booking.routeId?.destination || 'N/A',
                    departureTime: booking.routeId?.departureTime || 'N/A',
                    arrivalTime: booking.routeId?.arrivalTime || 'N/A',
                    duration: booking.routeId?.duration || 'N/A',
                    distance: booking.routeId?.distance || 0
                },
                seats: booking.seats,
                passengers: booking.passengerDetails,
                totalAmount: booking.totalAmount,
                taxAmount: booking.taxAmount,
                journeyDate: booking.journeyDate,
                paymentMethod: booking.paymentMethod,
                paymentStatus: booking.paymentStatus,
                bookingStatus: booking.bookingStatus,
                createdAt: booking.createdAt,
                boardingPoint: booking.boardingPoint,
                contactNumber: booking.contactNumber,
                email: booking.email
            }
        });
    } catch (error) {
        console.error('Error fetching booking:', error);
        res.status(500).json({ success: false, message: 'Error fetching booking', error: error.message });
    }
});

// ============= CANCEL BOOKING =============
router.put('/:bookingId/cancel', verifyToken, async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const { cancellationReason } = req.body;
        let booking;
        
        if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
            booking = await Booking.findById(req.params.bookingId).session(session);
        }
        
        if (!booking) {
            booking = await Booking.findOne({ bookingId: req.params.bookingId }).session(session);
        }
        
        if (!booking) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        
        if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
            await session.abortTransaction();
            session.endSession();
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        
        const travelDate = new Date(booking.travelDate);
        const now = new Date();
        const hoursDiff = (travelDate - now) / (1000 * 60 * 60);
        
        if (hoursDiff < 2 && req.user.role !== 'admin') {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({ success: false, message: 'Cannot cancel booking within 2 hours of departure' });
        }
        
        let refundAmount = booking.totalAmount;
        if (hoursDiff < 24 && hoursDiff >= 2) {
            refundAmount = booking.totalAmount * 0.8;
        } else if (hoursDiff < 2) {
            refundAmount = 0;
        }
        
        booking.bookingStatus = 'cancelled';
        booking.cancellationReason = cancellationReason;
        booking.cancelledAt = new Date();
        booking.refundAmount = refundAmount;
        
        await booking.save({ session });
        
        if (Seat) {
            const seatNumbers = booking.seats.map(s => s.seatNumber);
            await Seat.updateMany(
                { busId: booking.busId, seatNumber: { $in: seatNumbers } },
                { status: 'available', bookedBy: null, bookedAt: null },
                { session }
            );
        }
        
        await session.commitTransaction();
        session.endSession();
        
        res.json({ success: true, message: 'Booking cancelled successfully', data: { bookingId: booking.bookingId, refundAmount } });
    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        console.error('Error cancelling booking:', error);
        res.status(500).json({ success: false, message: 'Error cancelling booking', error: error.message });
    }
});

// ============= ADMIN: GET ALL BOOKINGS =============
router.get('/admin/all', verifyToken, isAdmin, async (req, res) => {
    try {
        const bookings = await Booking.find()
            .populate('userId', 'firstName lastName email phone')
            .populate('busId', 'busNumber busName busType operator')
            .populate('routeId', 'origin destination')
            .sort({ bookingDate: -1 });
        
        res.json({ success: true, data: bookings });
    } catch (error) {
        console.error('Error fetching all bookings:', error);
        res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
    }
});

// ============= ADMIN: UPDATE BOOKING STATUS =============
router.put('/admin/:bookingId/status', verifyToken, isAdmin, async (req, res) => {
    try {
        const { status } = req.body;
        let booking;
        
        if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
            booking = await Booking.findById(req.params.bookingId);
        }
        
        if (!booking) {
            booking = await Booking.findOne({ bookingId: req.params.bookingId });
        }
        
        if (!booking) {
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        
        booking.bookingStatus = status;
        await booking.save();
        
        res.json({ success: true, message: 'Booking status updated successfully', data: booking });
    } catch (error) {
        console.error('Error updating booking status:', error);
        res.status(500).json({ success: false, message: 'Error updating booking status', error: error.message });
    }
});

// ============= ADMIN: GET BUS SEATS WITH BOOKING DETAILS =============
router.get('/admin/bus-seats/:busId/:journeyDate', verifyToken, isAdmin, async (req, res) => {
    try {
        const { busId, journeyDate } = req.params;
        
        // Get all seats for this bus
        const allSeats = await Seat.find({ busId, isActive: true }).sort('seatNumber');
        
        // Get all confirmed, paid bookings for this bus and date
        const bookings = await Booking.find({
            busId,
            travelDate: new Date(journeyDate),
            bookingStatus: { $in: ['confirmed', 'completed'] },
            paymentStatus: 'completed'
        }).populate('userId', 'firstName lastName phone');
        
        // Collect all booked seats with passenger details
        const bookedSeatsMap = new Map();
        bookings.forEach(booking => {
            booking.seats.forEach(seat => {
                bookedSeatsMap.set(seat.seatNumber, {
                    seatNumber: seat.seatNumber,
                    passengerName: seat.passengerName,
                    passengerPhone: seat.passengerPhone,
                    bookingId: booking.bookingId,
                    userId: booking.userId,
                    bookingStatus: booking.bookingStatus
                });
            });
        });
        
        // Prepare seats with status and passenger info
        const seatsWithStatus = allSeats.map(seat => {
            const bookedInfo = bookedSeatsMap.get(seat.seatNumber);
            return {
                ...seat.toObject(),
                status: bookedInfo ? 'booked' : 'available',
                passenger: bookedInfo || null
            };
        });
        
        // Get bus details
        const bus = await Bus.findById(busId).populate('routeId', 'origin destination departureTime arrivalTime');
        
        res.json({
            success: true,
            data: {
                bus: bus,
                journeyDate: journeyDate,
                seats: seatsWithStatus,
                totalSeats: allSeats.length,
                bookedSeats: bookedSeatsMap.size,
                availableSeats: allSeats.length - bookedSeatsMap.size
            }
        });
    } catch (error) {
        console.error('Error fetching bus seats:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching bus seats',
            error: error.message
        });
    }
});
// ============= GET AVAILABLE SEATS =============
// ============= GET AVAILABLE SEATS (Public - No Auth Required) =============
// router.get('/seats/available/:busId/:travelDate', async (req, res) => {
//     try {
//         const { busId, travelDate } = req.params;
        
//         console.log(`🔍 Checking available seats for bus ${busId} on date ${travelDate}`);
        
//         // First, get the bus details to get the bus number
//         const bus = await Bus.findById(busId);
//         if (!bus) {
//             return res.status(404).json({
//                 success: false,
//                 message: 'Bus not found'
//             });
//         }
        
//         console.log(`📌 Bus found: ${bus.busNumber} - ${bus.busName}`);
        
//         // Parse the date correctly for full day
//         const startDate = new Date(travelDate);
//         startDate.setHours(0, 0, 0, 0);
//         const endDate = new Date(travelDate);
//         endDate.setHours(23, 59, 59, 999);
        
//         // Find all confirmed/completed bookings for this SPECIFIC BUS ID on this date
//         // This is the most reliable way - match by busId
//         const bookingsByBusId = await Booking.find({
//             busId: busId,  // Match by busId directly
//             journeyDate: { $gte: startDate, $lte: endDate },
//             status: { $in: ['confirmed', 'completed'] },
//             paymentStatus: 'paid'
//         }).select('seats bookingId busDetails.busNumber');
        
//         console.log(`📊 Found ${bookingsByBusId.length} bookings by busId`);
        
//         // Also find bookings by bus number (for backward compatibility)
//         const bookingsByBusNumber = await Booking.find({
//             'busDetails.busNumber': bus.busNumber,  // Match by bus number
//             journeyDate: { $gte: startDate, $lte: endDate },
//             status: { $in: ['confirmed', 'completed'] },
//             paymentStatus: 'paid',
//             busId: { $ne: busId }  // Exclude ones already found by busId
//         }).select('seats bookingId busDetails.busNumber');
        
//         console.log(`📊 Found ${bookingsByBusNumber.length} bookings by busNumber`);
        
//         // Combine both results
//         const allBookings = [...bookingsByBusId, ...bookingsByBusNumber];
        
//         // Collect all booked seats with details
//         const bookedSeats = [];
        
//         allBookings.forEach(booking => {
//             console.log(`Processing booking ${booking.bookingId} for bus ${booking.busDetails?.busNumber || 'unknown'}`);
            
//             // Check seats array
//             if (booking.seats && booking.seats.length > 0) {
//                 booking.seats.forEach(seat => {
//                     if (seat && seat.seatNumber) {
//                         bookedSeats.push({
//                             seatNumber: seat.seatNumber,
//                             passengerName: seat.passengerName || 'Booked',
//                             passengerPhone: seat.passengerPhone || 'N/A',
//                             bookingId: booking.bookingId,
//                             status: 'booked'
//                         });
//                         console.log(`📌 Booked seat: ${seat.seatNumber}`);
//                     }
//                 });
//             }
//         });
        
//         // Remove duplicates (in case same seat appears in multiple bookings - shouldn't happen)
//         const uniqueBookedSeats = [];
//         const seenSeats = new Set();
//         for (const seat of bookedSeats) {
//             if (!seenSeats.has(seat.seatNumber)) {
//                 seenSeats.add(seat.seatNumber);
//                 uniqueBookedSeats.push(seat);
//             }
//         }
        
//         console.log(`✅ Total unique booked seats for bus ${bus.busNumber}: ${uniqueBookedSeats.length}`);
//         console.log(`📋 Booked seats: ${uniqueBookedSeats.map(s => s.seatNumber).join(', ')}`);
        
//         res.json({
//             success: true,
//             data: uniqueBookedSeats,
//             count: uniqueBookedSeats.length,
//             busNumber: bus.busNumber,
//             travelDate: travelDate
//         });
        
//     } catch (error) {
//         console.error('❌ Error fetching available seats:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching seats',
//             error: error.message
//         });
//     }
// });


router.get('/seats/available/:busId/:travelDate', async (req, res) => {
    try {
        const { busId, travelDate } = req.params;
        
        console.log(`🔍 Checking available seats for bus ${busId} on date ${travelDate}`);
        
        // First, get the bus details
        const bus = await Bus.findById(busId);
        if (!bus) {
            return res.status(404).json({
                success: false,
                message: 'Bus not found'
            });
        }
        
        console.log(`📌 Bus found: ${bus.busNumber} - ${bus.busName}`);
        
        // Parse the date correctly for full day
        const startDate = new Date(travelDate);
        startDate.setHours(0, 0, 0, 0);
        const endDate = new Date(travelDate);
        endDate.setHours(23, 59, 59, 999);
        
        // Find all bookings for this bus on this date
        // Include both 'confirmed' and 'completed' status, and both 'paid' and 'pending' payment status
        const bookings = await Booking.find({
            busId: busId,
            journeyDate: { $gte: startDate, $lte: endDate },
            bookingStatus: { $in: ['confirmed', 'completed'] },
            paymentStatus: { $in: ['paid', 'pending'] }  // Include pending payments too
        }).select('seats bookingId');
        
        console.log(`📊 Found ${bookings.length} bookings for bus ${busId} on ${travelDate}`);
        
        // Collect all booked seats with details
        const bookedSeats = [];
        
        bookings.forEach(booking => {
            console.log(`Processing booking ${booking.bookingId}`);
            
            // Check seats array
            if (booking.seats && booking.seats.length > 0) {
                booking.seats.forEach(seat => {
                    if (seat && seat.seatNumber) {
                        bookedSeats.push({
                            seatNumber: seat.seatNumber,
                            passengerName: seat.passengerName || 'Booked',
                            passengerPhone: seat.passengerPhone || 'N/A',
                            bookingId: booking.bookingId,
                            status: 'booked'
                        });
                        console.log(`📌 Booked seat: ${seat.seatNumber}`);
                    }
                });
            }
        });
        
        // Remove duplicates
        const uniqueBookedSeats = [];
        const seenSeats = new Set();
        for (const seat of bookedSeats) {
            if (!seenSeats.has(seat.seatNumber)) {
                seenSeats.add(seat.seatNumber);
                uniqueBookedSeats.push(seat);
            }
        }
        
        console.log(`✅ Total booked seats: ${uniqueBookedSeats.length}`);
        console.log(`📋 Booked seats: ${uniqueBookedSeats.map(s => s.seatNumber).join(', ')}`);
        
        res.json({
            success: true,
            data: uniqueBookedSeats,
            count: uniqueBookedSeats.length,
            busNumber: bus.busNumber,
            travelDate: travelDate
        });
        
    } catch (error) {
        console.error('❌ Error fetching available seats:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching seats',
            error: error.message
        });
    }
});
module.exports = router;