
// const mongoose = require('mongoose');
// const express = require('express');
// const router = express.Router();
// const Booking = require('../models/bookingModel');
// const Bus = require('../models/busModel');
// const Seat = require('../models/seat');
// const Route = require('../models/routesModel');
// const { verifyToken, isAdmin } = require('../authMiddleware');

// // ============= CREATE BOOKING =============
// router.post('/', verifyToken, async (req, res) => {
//     const session = await mongoose.startSession();
//     session.startTransaction();
    
//     try {
//         const {
//             busId,
//             seats,
//             totalAmount,
//             taxAmount,
//             journeyDate,
//             paymentMethod,
//             paymentDetails,
//             boardingPoint
//         } = req.body;
        
//         // Validate required fields
//         if (!busId || !seats || !seats.length || !totalAmount || !paymentMethod || !journeyDate) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(400).json({
//                 success: false,
//                 message: 'Missing required fields'
//             });
//         }
        
//         // Get bus details
//         const bus = await Bus.findById(busId).session(session);
//         if (!bus) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(404).json({
//                 success: false,
//                 message: 'Bus not found'
//             });
//         }
        
//         // Get route details
//         const route = await Route.findById(bus.routeId).session(session);
//         if (!route) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(404).json({
//                 success: false,
//                 message: 'Route not found for this bus'
//             });
//         }
        
//         // Check if seats are still available
//         const bookedSeats = await Booking.find({
//             busId,
//             travelDate: new Date(journeyDate),
//             bookingStatus: 'confirmed',
//             paymentStatus: 'completed',
//             $or: [
//                 { 'selectedSeats.seatNumber': { $in: seats.map(s => s.seatNumber) } },
//                 { 'seats.seatNumber': { $in: seats.map(s => s.seatNumber) } }
//             ]
//         }).session(session);
        
//         if (bookedSeats.length > 0) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(400).json({
//                 success: false,
//                 message: 'Some seats are no longer available'
//             });
//         }
        
//         // Create booking (bookingId will be auto-generated by pre-save hook)
//         const booking = new Booking({
//             userId: req.user.userId,
//             busId: busId,
//             routeId: bus.routeId,
//             seats: seats.map(s => ({
//                 seatNumber: s.seatNumber,
//                 passengerName: s.passengerName,
//                 passengerAge: Number(s.passengerAge),
//                 passengerGender: s.passengerGender,
//                 passengerPhone: s.passengerPhone,
//                 passengerEmail: s.passengerEmail || ''
//             })),
//             selectedSeats: seats.map(s => ({
//                 seatNumber: s.seatNumber,
//                 seatType: 'passenger',
//                 price: totalAmount / seats.length
//             })),
//             passengerDetails: seats.map(s => ({
//                 name: s.passengerName,
//                 age: Number(s.passengerAge),
//                 gender: s.passengerGender,
//                 seatNumber: s.seatNumber,
//                 phone: s.passengerPhone,
//                 email: s.passengerEmail || ''
//             })),
//             totalAmount: Number(totalAmount),
//             taxAmount: Number(taxAmount) || 0,
//             paymentMethod: paymentMethod,
//             paymentStatus: paymentMethod === 'cash' ? 'pending' : 'completed',
//             paymentDetails: paymentDetails || {},
//             boardingPoint: boardingPoint || '',
//             bookingStatus: 'confirmed',
//             travelDate: new Date(journeyDate),
//             journeyDate: new Date(journeyDate),
//             contactNumber: seats[0]?.passengerPhone || '',
//             email: seats[0]?.passengerEmail || ''
//         });
        
//         await booking.save({ session });
        
//         // Update seat status if Seat model exists
//         if (Seat) {
//             await Seat.updateMany(
//                 {
//                     busId: busId,
//                     seatNumber: { $in: seats.map(s => s.seatNumber) }
//                 },
//                 { status: 'booked', bookedBy: req.user.userId, bookedAt: new Date() },
//                 { session }
//             );
//         }
        
//         await session.commitTransaction();
//         session.endSession();
        
//         // Populate and return the booking
//         const populatedBooking = await Booking.findById(booking._id)
//             .populate('busId', 'busName busNumber busType operator')
//             .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        
//         const responseData = {
//             _id: populatedBooking._id,
//             bookingId: populatedBooking.bookingId,
//             busDetails: {
//                 busName: populatedBooking.busId?.busName || 'N/A',
//                 busNumber: populatedBooking.busId?.busNumber || 'N/A',
//                 busType: populatedBooking.busId?.busType || 'N/A',
//                 operator: populatedBooking.busId?.operator || 'N/A'
//             },
//             routeDetails: {
//                 origin: populatedBooking.routeId?.origin || 'N/A',
//                 destination: populatedBooking.routeId?.destination || 'N/A',
//                 departureTime: populatedBooking.routeId?.departureTime || 'N/A',
//                 arrivalTime: populatedBooking.routeId?.arrivalTime || 'N/A',
//                 duration: populatedBooking.routeId?.duration || 'N/A',
//                 distance: populatedBooking.routeId?.distance || 0
//             },
//             seats: populatedBooking.seats,
//             passengers: populatedBooking.passengerDetails,
//             totalAmount: populatedBooking.totalAmount,
//             taxAmount: populatedBooking.taxAmount,
//             journeyDate: populatedBooking.journeyDate,
//             paymentMethod: populatedBooking.paymentMethod,
//             paymentStatus: populatedBooking.paymentStatus,
//             bookingStatus: populatedBooking.bookingStatus,
//             createdAt: populatedBooking.createdAt,
//             boardingPoint: populatedBooking.boardingPoint
//         };
        
//         res.status(201).json({
//             success: true,
//             message: 'Booking created successfully',
//             data: responseData
//         });
        
//     } catch (error) {
//         await session.abortTransaction();
//         session.endSession();
//         console.error('Error creating booking:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error creating booking',
//             error: error.message
//         });
//     }
// });

// // ============= GET USER'S BOOKINGS =============
// router.get('/my-bookings', verifyToken, async (req, res) => {
//     try {
//         const bookings = await Booking.find({ userId: req.user.userId })
//             .populate('busId', 'busName busNumber busType operator')
//             .populate('routeId', 'origin destination departureTime arrivalTime duration')
//             .sort({ bookingDate: -1 });
        
//         const formattedBookings = bookings.map(booking => ({
//             _id: booking._id,
//             bookingId: booking.bookingId,
//             busDetails: {
//                 busName: booking.busId?.busName || 'N/A',
//                 busNumber: booking.busId?.busNumber || 'N/A',
//                 busType: booking.busId?.busType || 'N/A',
//                 operator: booking.busId?.operator || 'N/A'
//             },
//             routeDetails: {
//                 origin: booking.routeId?.origin || 'N/A',
//                 destination: booking.routeId?.destination || 'N/A',
//                 departureTime: booking.routeId?.departureTime || 'N/A',
//                 arrivalTime: booking.routeId?.arrivalTime || 'N/A',
//                 duration: booking.routeId?.duration || 'N/A'
//             },
//             seats: booking.seats,
//             totalAmount: booking.totalAmount,
//             taxAmount: booking.taxAmount,
//             journeyDate: booking.journeyDate,
//             paymentMethod: booking.paymentMethod,
//             paymentStatus: booking.paymentStatus,
//             bookingStatus: booking.bookingStatus,
//             createdAt: booking.createdAt,
//             boardingPoint: booking.boardingPoint
//         }));
        
//         res.json({ success: true, data: formattedBookings });
//     } catch (error) {
//         console.error('Error fetching bookings:', error);
//         res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
//     }
// });

// // ============= GET BOOKING BY ID =============
// router.get('/:bookingId', verifyToken, async (req, res) => {
//     try {
//         let booking;
        
//         if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
//             booking = await Booking.findById(req.params.bookingId)
//                 .populate('busId', 'busName busNumber busType operator')
//                 .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
//         }
        
//         if (!booking) {
//             booking = await Booking.findOne({ bookingId: req.params.bookingId })
//                 .populate('busId', 'busName busNumber busType operator')
//                 .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
//         }
        
//         if (!booking) {
//             return res.status(404).json({ success: false, message: 'Booking not found' });
//         }
        
//         if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
//             return res.status(403).json({ success: false, message: 'Access denied' });
//         }
        
//         res.json({
//             success: true,
//             data: {
//                 _id: booking._id,
//                 bookingId: booking.bookingId,
//                 busDetails: {
//                     busName: booking.busId?.busName || 'N/A',
//                     busNumber: booking.busId?.busNumber || 'N/A',
//                     busType: booking.busId?.busType || 'N/A',
//                     operator: booking.busId?.operator || 'N/A'
//                 },
//                 routeDetails: {
//                     origin: booking.routeId?.origin || 'N/A',
//                     destination: booking.routeId?.destination || 'N/A',
//                     departureTime: booking.routeId?.departureTime || 'N/A',
//                     arrivalTime: booking.routeId?.arrivalTime || 'N/A',
//                     duration: booking.routeId?.duration || 'N/A',
//                     distance: booking.routeId?.distance || 0
//                 },
//                 seats: booking.seats,
//                 passengers: booking.passengerDetails,
//                 totalAmount: booking.totalAmount,
//                 taxAmount: booking.taxAmount,
//                 journeyDate: booking.journeyDate,
//                 paymentMethod: booking.paymentMethod,
//                 paymentStatus: booking.paymentStatus,
//                 bookingStatus: booking.bookingStatus,
//                 createdAt: booking.createdAt,
//                 boardingPoint: booking.boardingPoint,
//                 contactNumber: booking.contactNumber,
//                 email: booking.email
//             }
//         });
//     } catch (error) {
//         console.error('Error fetching booking:', error);
//         res.status(500).json({ success: false, message: 'Error fetching booking', error: error.message });
//     }
// });

// // ============= CANCEL BOOKING =============
// router.put('/:bookingId/cancel', verifyToken, async (req, res) => {
//     const session = await mongoose.startSession();
//     session.startTransaction();
    
//     try {
//         const { cancellationReason } = req.body;
//         let booking;
        
//         if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
//             booking = await Booking.findById(req.params.bookingId).session(session);
//         }
        
//         if (!booking) {
//             booking = await Booking.findOne({ bookingId: req.params.bookingId }).session(session);
//         }
        
//         if (!booking) {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(404).json({ success: false, message: 'Booking not found' });
//         }
        
//         if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(403).json({ success: false, message: 'Access denied' });
//         }
        
//         const travelDate = new Date(booking.travelDate);
//         const now = new Date();
//         const hoursDiff = (travelDate - now) / (1000 * 60 * 60);
        
//         if (hoursDiff < 2 && req.user.role !== 'admin') {
//             await session.abortTransaction();
//             session.endSession();
//             return res.status(400).json({ success: false, message: 'Cannot cancel booking within 2 hours of departure' });
//         }
        
//         let refundAmount = booking.totalAmount;
//         if (hoursDiff < 24 && hoursDiff >= 2) {
//             refundAmount = booking.totalAmount * 0.8;
//         } else if (hoursDiff < 2) {
//             refundAmount = 0;
//         }
        
//         booking.bookingStatus = 'cancelled';
//         booking.cancellationReason = cancellationReason;
//         booking.cancelledAt = new Date();
//         booking.refundAmount = refundAmount;
        
//         await booking.save({ session });
        
//         if (Seat) {
//             const seatNumbers = booking.seats.map(s => s.seatNumber);
//             await Seat.updateMany(
//                 { busId: booking.busId, seatNumber: { $in: seatNumbers } },
//                 { status: 'available', bookedBy: null, bookedAt: null },
//                 { session }
//             );
//         }
        
//         await session.commitTransaction();
//         session.endSession();
        
//         res.json({ success: true, message: 'Booking cancelled successfully', data: { bookingId: booking.bookingId, refundAmount } });
//     } catch (error) {
//         await session.abortTransaction();
//         session.endSession();
//         console.error('Error cancelling booking:', error);
//         res.status(500).json({ success: false, message: 'Error cancelling booking', error: error.message });
//     }
// });

// // ============= ADMIN: GET ALL BOOKINGS =============
// router.get('/admin/all', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const bookings = await Booking.find()
//             .populate('userId', 'firstName lastName email phone')
//             .populate('busId', 'busNumber busName busType operator')
//             .populate('routeId', 'origin destination')
//             .sort({ bookingDate: -1 });
        
//         res.json({ success: true, data: bookings });
//     } catch (error) {
//         console.error('Error fetching all bookings:', error);
//         res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
//     }
// });

// // ============= ADMIN: UPDATE BOOKING STATUS =============
// router.put('/admin/:bookingId/status', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const { status } = req.body;
//         let booking;
        
//         if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
//             booking = await Booking.findById(req.params.bookingId);
//         }
        
//         if (!booking) {
//             booking = await Booking.findOne({ bookingId: req.params.bookingId });
//         }
        
//         if (!booking) {
//             return res.status(404).json({ success: false, message: 'Booking not found' });
//         }
        
//         booking.bookingStatus = status;
//         await booking.save();
        
//         res.json({ success: true, message: 'Booking status updated successfully', data: booking });
//     } catch (error) {
//         console.error('Error updating booking status:', error);
//         res.status(500).json({ success: false, message: 'Error updating booking status', error: error.message });
//     }
// });

// // ============= ADMIN: GET BUS SEATS WITH BOOKING DETAILS =============
// router.get('/admin/bus-seats/:busId/:journeyDate', verifyToken, isAdmin, async (req, res) => {
//     try {
//         const { busId, journeyDate } = req.params;
        
//         // Get all seats for this bus
//         const allSeats = await Seat.find({ busId, isActive: true }).sort('seatNumber');
        
//         // Get all confirmed, paid bookings for this bus and date
//         const bookings = await Booking.find({
//             busId,
//             travelDate: new Date(journeyDate),
//             bookingStatus: { $in: ['confirmed', 'completed'] },
//             paymentStatus: 'completed'
//         }).populate('userId', 'firstName lastName phone');
        
//         // Collect all booked seats with passenger details
//         const bookedSeatsMap = new Map();
//         bookings.forEach(booking => {
//             booking.seats.forEach(seat => {
//                 bookedSeatsMap.set(seat.seatNumber, {
//                     seatNumber: seat.seatNumber,
//                     passengerName: seat.passengerName,
//                     passengerPhone: seat.passengerPhone,
//                     bookingId: booking.bookingId,
//                     userId: booking.userId,
//                     bookingStatus: booking.bookingStatus
//                 });
//             });
//         });
        
//         // Prepare seats with status and passenger info
//         const seatsWithStatus = allSeats.map(seat => {
//             const bookedInfo = bookedSeatsMap.get(seat.seatNumber);
//             return {
//                 ...seat.toObject(),
//                 status: bookedInfo ? 'booked' : 'available',
//                 passenger: bookedInfo || null
//             };
//         });
        
//         // Get bus details
//         const bus = await Bus.findById(busId).populate('routeId', 'origin destination departureTime arrivalTime');
        
//         res.json({
//             success: true,
//             data: {
//                 bus: bus,
//                 journeyDate: journeyDate,
//                 seats: seatsWithStatus,
//                 totalSeats: allSeats.length,
//                 bookedSeats: bookedSeatsMap.size,
//                 availableSeats: allSeats.length - bookedSeatsMap.size
//             }
//         });
//     } catch (error) {
//         console.error('Error fetching bus seats:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching bus seats',
//             error: error.message
//         });
//     }
// });



// router.get('/seats/available/:busId/:travelDate', async (req, res) => {
//     try {
//         const { busId, travelDate } = req.params;
        
//         console.log(`🔍 Checking available seats for bus ${busId} on date ${travelDate}`);
        
//         // First, get the bus details
//         const bus = await Bus.findById(busId);
//         if (!bus) {
//             return res.status(404).json({
//                 success: false,
//                 message: 'Bus not found'
//             });
//         }
        
//         console.log(`📌 Bus found: ${bus.busNumber} - ${bus.busName}`);
        
//         // Parse the date correctly for full day
//         const startDate = new Date(travelDate);
//         startDate.setHours(0, 0, 0, 0);
//         const endDate = new Date(travelDate);
//         endDate.setHours(23, 59, 59, 999);
        
//         // Find all bookings for this bus on this date
//         // Include both 'confirmed' and 'completed' status, and both 'paid' and 'pending' payment status
//         const bookings = await Booking.find({
//             busId: busId,
//             journeyDate: { $gte: startDate, $lte: endDate },
//             bookingStatus: { $in: ['confirmed', 'completed'] },
//             paymentStatus: { $in: ['paid', 'pending'] }  // Include pending payments too
//         }).select('seats bookingId');
        
//         console.log(`📊 Found ${bookings.length} bookings for bus ${busId} on ${travelDate}`);
        
//         // Collect all booked seats with details
//         const bookedSeats = [];
        
//         bookings.forEach(booking => {
//             console.log(`Processing booking ${booking.bookingId}`);
            
//             // Check seats array
//             if (booking.seats && booking.seats.length > 0) {
//                 booking.seats.forEach(seat => {
//                     if (seat && seat.seatNumber) {
//                         bookedSeats.push({
//                             seatNumber: seat.seatNumber,
//                             passengerName: seat.passengerName || 'Booked',
//                             passengerPhone: seat.passengerPhone || 'N/A',
//                             bookingId: booking.bookingId,
//                             status: 'booked'
//                         });
//                         console.log(`📌 Booked seat: ${seat.seatNumber}`);
//                     }
//                 });
//             }
//         });
        
//         // Remove duplicates
//         const uniqueBookedSeats = [];
//         const seenSeats = new Set();
//         for (const seat of bookedSeats) {
//             if (!seenSeats.has(seat.seatNumber)) {
//                 seenSeats.add(seat.seatNumber);
//                 uniqueBookedSeats.push(seat);
//             }
//         }
        
//         console.log(`✅ Total booked seats: ${uniqueBookedSeats.length}`);
//         console.log(`📋 Booked seats: ${uniqueBookedSeats.map(s => s.seatNumber).join(', ')}`);
        
//         res.json({
//             success: true,
//             data: uniqueBookedSeats,
//             count: uniqueBookedSeats.length,
//             busNumber: bus.busNumber,
//             travelDate: travelDate
//         });
        
//     } catch (error) {
//         console.error('❌ Error fetching available seats:', error);
//         res.status(500).json({
//             success: false,
//             message: 'Error fetching seats',
//             error: error.message
//         });
//     }
// });
// module.exports = router;



const mongoose = require('mongoose');
const express = require('express');
const router = express.Router();
const Booking = require('../models/bookingModel');
const Bus = require('../models/busModel');
const Seat = require('../models/seat');
const Route = require('../models/routesModel');
const { verifyToken, isAdmin } = require('../authMiddleware');

// ============= TEST ROUTE (Add this at the top) =============
router.get('/test', (req, res) => {
    console.log('✅ TEST ROUTE HIT - Booking routes are working!');
    res.json({
        success: true,
        message: 'Booking routes are working!',
        endpoints: [
            'POST /api/bookings/ - Create booking',
            'GET /api/bookings/test - Test endpoint',
            'GET /api/bookings/my-bookings - Get user bookings',
            'GET /api/bookings/seats/available/:busId/:travelDate - Get available seats'
        ]
    });
});

// ============= CREATE BOOKING =============
router.post('/', verifyToken, async (req, res) => {
    console.log('📝 CREATE BOOKING - Request received');
    console.log('User from token:', req.user);
    console.log('Request body:', JSON.stringify(req.body, null, 2));
    
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const {
            busId,
            seats,
            totalAmount,
            taxAmount,
            journeyDate,
            paymentMethod,
            paymentDetails,
            boardingPoint
        } = req.body;
        
        // Validate required fields
        if (!busId || !seats || !seats.length || !totalAmount || !paymentMethod || !journeyDate) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Missing required fields',
                required: ['busId', 'seats', 'totalAmount', 'paymentMethod', 'journeyDate']
            });
        }
        
        // Get bus details
        const bus = await Bus.findById(busId).session(session);
        if (!bus) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Bus not found'
            });
        }
        
        // Get route details
        const route = await Route.findById(bus.routeId).session(session);
        if (!route) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Route not found for this bus'
            });
        }
        
        // Parse date correctly
        const travelDateObj = new Date(journeyDate);
        travelDateObj.setHours(0, 0, 0, 0);
        
        // Check if seats are still available
        const seatNumbers = seats.map(s => s.seatNumber);
        const bookedSeats = await Booking.find({
            busId: busId,
            travelDate: {
                $gte: travelDateObj,
                $lt: new Date(travelDateObj.getTime() + 24 * 60 * 60 * 1000)
            },
            bookingStatus: { $in: ['confirmed', 'completed'] },
            paymentStatus: 'completed',
            'seats.seatNumber': { $in: seatNumbers }
        }).session(session);
        
        if (bookedSeats.length > 0) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Some seats are no longer available',
                bookedSeats: bookedSeats.flatMap(b => b.seats.map(s => s.seatNumber))
            });
        }
        
        // Create booking
        const booking = new Booking({
            userId: req.user.userId,
            busId: busId,
            routeId: bus.routeId,
            seats: seats.map(s => ({
                seatNumber: s.seatNumber,
                passengerName: s.passengerName,
                passengerAge: Number(s.passengerAge),
                passengerGender: s.passengerGender,
                passengerPhone: s.passengerPhone,
                passengerEmail: s.passengerEmail || ''
            })),
            selectedSeats: seats.map(s => ({
                seatNumber: s.seatNumber,
                seatType: 'passenger',
                price: totalAmount / seats.length
            })),
            passengerDetails: seats.map(s => ({
                name: s.passengerName,
                age: Number(s.passengerAge),
                gender: s.passengerGender,
                seatNumber: s.seatNumber,
                phone: s.passengerPhone,
                email: s.passengerEmail || ''
            })),
            totalAmount: Number(totalAmount),
            taxAmount: Number(taxAmount) || 0,
            paymentMethod: paymentMethod,
            paymentStatus: paymentMethod === 'cash' ? 'pending' : 'completed',
            paymentDetails: paymentDetails || {},
            boardingPoint: boardingPoint || '',
            bookingStatus: 'confirmed',
            travelDate: travelDateObj,
            journeyDate: travelDateObj,
            contactNumber: seats[0]?.passengerPhone || '',
            email: seats[0]?.passengerEmail || '',
            bookingDate: new Date()
        });
        
        await booking.save({ session });
        console.log(`✅ Booking saved with ID: ${booking.bookingId}`);
        
        // Update seat status if Seat model exists
        if (Seat) {
            await Seat.updateMany(
                {
                    busId: busId,
                    seatNumber: { $in: seatNumbers }
                },
                { 
                    status: 'booked', 
                    bookedBy: req.user.userId, 
                    bookedAt: new Date() 
                },
                { session }
            );
        }
        
        await session.commitTransaction();
        session.endSession();
        
        // Populate and return the booking
        const populatedBooking = await Booking.findById(booking._id)
            .populate('busId', 'busName busNumber busType operator')
            .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        
        res.status(201).json({
            success: true,
            message: 'Booking created successfully',
            data: {
                _id: populatedBooking._id,
                bookingId: populatedBooking.bookingId,
                busDetails: {
                    busName: populatedBooking.busId?.busName || 'N/A',
                    busNumber: populatedBooking.busId?.busNumber || 'N/A',
                    busType: populatedBooking.busId?.busType || 'N/A',
                    operator: populatedBooking.busId?.operator || 'N/A'
                },
                routeDetails: {
                    origin: populatedBooking.routeId?.origin || 'N/A',
                    destination: populatedBooking.routeId?.destination || 'N/A',
                    departureTime: populatedBooking.routeId?.departureTime || 'N/A',
                    arrivalTime: populatedBooking.routeId?.arrivalTime || 'N/A',
                    duration: populatedBooking.routeId?.duration || 'N/A',
                    distance: populatedBooking.routeId?.distance || 0
                },
                seats: populatedBooking.seats,
                passengers: populatedBooking.passengerDetails,
                totalAmount: populatedBooking.totalAmount,
                taxAmount: populatedBooking.taxAmount,
                journeyDate: populatedBooking.journeyDate,
                paymentMethod: populatedBooking.paymentMethod,
                paymentStatus: populatedBooking.paymentStatus,
                bookingStatus: populatedBooking.bookingStatus,
                createdAt: populatedBooking.createdAt,
                boardingPoint: populatedBooking.boardingPoint
            }
        });
        
    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        console.error('❌ Error creating booking:', error);
        res.status(500).json({
            success: false,
            message: 'Error creating booking',
            error: error.message
        });
    }
});

// ============= GET USER'S BOOKINGS =============
router.get('/my-bookings', verifyToken, async (req, res) => {
    try {
        const bookings = await Booking.find({ userId: req.user.userId })
            .populate('busId', 'busName busNumber busType operator')
            .populate('routeId', 'origin destination departureTime arrivalTime duration')
            .sort({ bookingDate: -1 });
        
        res.json({ success: true, data: bookings });
    } catch (error) {
        console.error('Error fetching bookings:', error);
        res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
    }
});

// ============= GET BOOKING BY ID =============
router.get('/:bookingId', verifyToken, async (req, res) => {
    try {
        let booking;
        
        if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
            booking = await Booking.findById(req.params.bookingId)
                .populate('busId', 'busName busNumber busType operator')
                .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        }
        
        if (!booking) {
            booking = await Booking.findOne({ bookingId: req.params.bookingId })
                .populate('busId', 'busName busNumber busType operator')
                .populate('routeId', 'origin destination departureTime arrivalTime duration distance');
        }
        
        if (!booking) {
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        
        if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        
        res.json({ success: true, data: booking });
    } catch (error) {
        console.error('Error fetching booking:', error);
        res.status(500).json({ success: false, message: 'Error fetching booking', error: error.message });
    }
});

// ============= CANCEL BOOKING =============
router.put('/:bookingId/cancel', verifyToken, async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const { cancellationReason } = req.body;
        let booking;
        
        if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
            booking = await Booking.findById(req.params.bookingId).session(session);
        }
        
        if (!booking) {
            booking = await Booking.findOne({ bookingId: req.params.bookingId }).session(session);
        }
        
        if (!booking) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        
        if (booking.userId.toString() !== req.user.userId && req.user.role !== 'admin') {
            await session.abortTransaction();
            session.endSession();
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        
        const travelDate = new Date(booking.travelDate);
        const now = new Date();
        const hoursDiff = (travelDate - now) / (1000 * 60 * 60);
        
        if (hoursDiff < 2 && req.user.role !== 'admin') {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({ success: false, message: 'Cannot cancel booking within 2 hours of departure' });
        }
        
        let refundAmount = booking.totalAmount;
        if (hoursDiff < 24 && hoursDiff >= 2) {
            refundAmount = booking.totalAmount * 0.8;
        } else if (hoursDiff < 2) {
            refundAmount = 0;
        }
        
        booking.bookingStatus = 'cancelled';
        booking.cancellationReason = cancellationReason;
        booking.cancelledAt = new Date();
        booking.refundAmount = refundAmount;
        
        await booking.save({ session });
        
        if (Seat) {
            const seatNumbers = booking.seats.map(s => s.seatNumber);
            await Seat.updateMany(
                { busId: booking.busId, seatNumber: { $in: seatNumbers } },
                { status: 'available', bookedBy: null, bookedAt: null },
                { session }
            );
        }
        
        await session.commitTransaction();
        session.endSession();
        
        res.json({ success: true, message: 'Booking cancelled successfully', data: { bookingId: booking.bookingId, refundAmount } });
    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        console.error('Error cancelling booking:', error);
        res.status(500).json({ success: false, message: 'Error cancelling booking', error: error.message });
    }
});

// ============= GET AVAILABLE SEATS =============
router.get('/seats/available/:busId/:travelDate', async (req, res) => {
    try {
        const { busId, travelDate } = req.params;
        
        console.log(`🔍 Checking available seats for bus ${busId} on date ${travelDate}`);
        
        const bus = await Bus.findById(busId);
        if (!bus) {
            return res.status(404).json({
                success: false,
                message: 'Bus not found'
            });
        }
        
        const startDate = new Date(travelDate);
        startDate.setHours(0, 0, 0, 0);
        const endDate = new Date(travelDate);
        endDate.setHours(23, 59, 59, 999);
        
        const bookings = await Booking.find({
            busId: busId,
            travelDate: { $gte: startDate, $lte: endDate },
            bookingStatus: { $in: ['confirmed', 'completed'] }
        }).select('seats bookingId');
        
        const bookedSeats = [];
        bookings.forEach(booking => {
            if (booking.seats && booking.seats.length > 0) {
                booking.seats.forEach(seat => {
                    if (seat && seat.seatNumber) {
                        bookedSeats.push({
                            seatNumber: seat.seatNumber,
                            passengerName: seat.passengerName || 'Booked',
                            passengerPhone: seat.passengerPhone || 'N/A',
                            bookingId: booking.bookingId,
                            status: 'booked'
                        });
                    }
                });
            }
        });
        
        // Remove duplicates
        const uniqueBookedSeats = [];
        const seenSeats = new Set();
        for (const seat of bookedSeats) {
            if (!seenSeats.has(seat.seatNumber)) {
                seenSeats.add(seat.seatNumber);
                uniqueBookedSeats.push(seat);
            }
        }
        
        res.json({
            success: true,
            data: uniqueBookedSeats,
            count: uniqueBookedSeats.length,
            busNumber: bus.busNumber,
            travelDate: travelDate
        });
        
    } catch (error) {
        console.error('❌ Error fetching available seats:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching seats',
            error: error.message
        });
    }
});

// ============= ADMIN ENDPOINTS =============
router.get('/admin/all', verifyToken, isAdmin, async (req, res) => {
    try {
        const bookings = await Booking.find()
            .populate('userId', 'firstName lastName email phone')
            .populate('busId', 'busNumber busName busType operator')
            .populate('routeId', 'origin destination')
            .sort({ bookingDate: -1 });
        
        res.json({ success: true, data: bookings });
    } catch (error) {
        console.error('Error fetching all bookings:', error);
        res.status(500).json({ success: false, message: 'Error fetching bookings', error: error.message });
    }
});

router.put('/admin/:bookingId/status', verifyToken, isAdmin, async (req, res) => {
    try {
        const { status } = req.body;
        let booking;
        
        if (mongoose.Types.ObjectId.isValid(req.params.bookingId)) {
            booking = await Booking.findById(req.params.bookingId);
        }
        
        if (!booking) {
            booking = await Booking.findOne({ bookingId: req.params.bookingId });
        }
        
        if (!booking) {
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        
        booking.bookingStatus = status;
        await booking.save();
        
        res.json({ success: true, message: 'Booking status updated successfully', data: booking });
    } catch (error) {
        console.error('Error updating booking status:', error);
        res.status(500).json({ success: false, message: 'Error updating booking status', error: error.message });
    }
});

router.get('/admin/bus-seats/:busId/:journeyDate', verifyToken, isAdmin, async (req, res) => {
    try {
        const { busId, journeyDate } = req.params;
        
        const allSeats = await Seat.find({ busId, isActive: true }).sort('seatNumber');
        
        const startDate = new Date(journeyDate);
        startDate.setHours(0, 0, 0, 0);
        const endDate = new Date(journeyDate);
        endDate.setHours(23, 59, 59, 999);
        
        const bookings = await Booking.find({
            busId,
            travelDate: { $gte: startDate, $lte: endDate },
            bookingStatus: { $in: ['confirmed', 'completed'] },
            paymentStatus: 'completed'
        }).populate('userId', 'firstName lastName phone');
        
        const bookedSeatsMap = new Map();
        bookings.forEach(booking => {
            booking.seats.forEach(seat => {
                bookedSeatsMap.set(seat.seatNumber, {
                    seatNumber: seat.seatNumber,
                    passengerName: seat.passengerName,
                    passengerPhone: seat.passengerPhone,
                    bookingId: booking.bookingId,
                    userId: booking.userId,
                    bookingStatus: booking.bookingStatus
                });
            });
        });
        
        const seatsWithStatus = allSeats.map(seat => {
            const bookedInfo = bookedSeatsMap.get(seat.seatNumber);
            return {
                ...seat.toObject(),
                status: bookedInfo ? 'booked' : 'available',
                passenger: bookedInfo || null
            };
        });
        
        const bus = await Bus.findById(busId).populate('routeId', 'origin destination departureTime arrivalTime');
        
        res.json({
            success: true,
            data: {
                bus: bus,
                journeyDate: journeyDate,
                seats: seatsWithStatus,
                totalSeats: allSeats.length,
                bookedSeats: bookedSeatsMap.size,
                availableSeats: allSeats.length - bookedSeatsMap.size
            }
        });
    } catch (error) {
        console.error('Error fetching bus seats:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching bus seats',
            error: error.message
        });
    }
});

module.exports = router;